--if not config.msbuild_lsp then
--config.msbuild_lsp = {
--default_config = {
--cmd = { 'dotnet',
--'C:/CsharpTool/msbuild-project-tools-server/out/language-server/MSBuildProjectTools.LanguageServer.Host.dll' },
--filetypes = { 'csproj', 'fsproj', 'vbproj', 'xml' }, -- Add other project filetypes if needed
--root_dir = function(fname)
--return lspconfig.util.root_pattern('*.sln', '*.csproj', '*.fsproj', '*.vbproj')(fname) or
--vim.loop.os_homedir()
--end,
--settings = {},
--}
--}
--end
