require("pack.hooks_build")
require("pack.lualine")
require("pack.theme")

if not vim.o.diff then
	require("pack.blink")
	require("pack.conform")
	require("pack.harpoon")
	require("pack.surround")
	require("pack.treesitter-manager")
	require("pack.trouble")
	require("pack.telescope")
	require("pack.oil")
	require("pack.mason")
	require("pack.lsp-config")
	require("pack.lazydev")
	require("pack.todo-comments")
	require("pack.extension")
	require("pack.comment")
end
-- require("pack.luasnip")
