--require("conform").setup({
--	formatter_by_ft = {
--		lua = { "stylua" },
--		cpp = { "clang-format" },
--
--		-- Conform will notify you when a formatter errors
--	},
--	--clang_format_options = { style = "file" },
--	formatters = {
--		clang_format = {
--			prepend_args = {"--style:file"},
--		}
--	},
--	notify_on_error = true,
--})
